function renderTeams(){let a=C.slice().sort((x,y)=>rating(y)-rating(x));return'<div class="sectionhead"><div><h1>48개 참가국</h1><p>국가를 누르면 전력·핵심 선수·단계별 확률 확인 가능</p></div></div><div class="cards">'+a.map(c=>'<button class="teamcard" onclick="openTeam(\''+c+'\')"><div>'+team(c)+'</div><small>'+T[c][2]+'조 · 전력 '+rating(c)+'</small><div class="metrics"><div><b>'+pct(S.teams[c].r32)+'</b><span>32강</span></div><div><b>'+pct(S.teams[c].fin)+'</b><span>결승</span></div><div><b>'+pct(S.teams[c].win)+'</b><span>우승</span></div></div></button>').join('')+'</div>'}
function moneyTier(v){
  let tiers=[
    {min:1000000000000,key:'obsidian',name:'흑요석',next:null},
    {min:100000000000,key:'ruby',name:'루비',next:1000000000000},
    {min:10000000000,key:'diamond',name:'다이아',next:100000000000},
    {min:1000000000,key:'platinum',name:'플레티넘',next:10000000000},
    {min:100000000,key:'gold',name:'금색 철',next:1000000000},
    {min:10000000,key:'silver',name:'은색 철',next:100000000},
    {min:1000000,key:'bronze',name:'동색 철',next:10000000},
    {min:0,key:'basic',name:'일반',next:1000000}
  ];return tiers.find(x=>v>=x.min)
}
const STAR_TIERS=[['white','흰색'],['bronze','동'],['silver','은'],['gold','금'],['platinum','플레티넘'],['diamond','다이아'],['ruby','루비'],['obsidian','흑요석']];
function starSlots(count){
  count=Math.max(0,Math.floor(count||0));let slots=[];
  if(count<=10){for(let i=0;i<10;i++)slots.push(i<count?'white':'empty')}
  else if(count>=80){slots=Array(10).fill('obsidian')}
  else{let tier=Math.floor((count-1)/10),progress=(count-1)%10+1,prev=tier-1;for(let i=0;i<10-progress;i++)slots.push(STAR_TIERS[prev][0]);for(let i=0;i<progress;i++)slots.push(STAR_TIERS[tier][0])}
  return'<div class="star-grid">'+slots.map((x,i)=>'<span class="achievement-star '+x+'" title="업적 별 '+(i+1)+'">★</span>').join('')+'</div>'
}
function starTierText(count){if(!count)return'우승 베팅 적중 시 흰색 별 획득';if(count>=80)return'흑요석 별 완성';let tier=Math.floor((count-1)/10),progress=(count-1)%10+1;return STAR_TIERS[tier][1]+' 별 '+progress+'/10'}
function syncVaultAmount(){let e=document.getElementById('vaultAmount');if(e)e.value=vaultAmount}
function addVaultAmount(v){vaultAmount=Math.max(0,Math.floor(vaultAmount+v));syncVaultAmount()}
function setVaultAmount(v){vaultAmount=Math.max(0,Math.floor(+v||0));syncVaultAmount()}
function clearVaultAmount(){vaultAmount=0;syncVaultAmount()}
function maxVaultAmount(mode){vaultAmount=mode==='deposit'?Math.max(0,Math.floor(S.wallet.bal)):Math.max(0,Math.floor(S.wallet.vault));syncVaultAmount()}
function vaultTransaction(type){
  let a=Math.floor(vaultAmount);if(!a||a<1)return alert('금액을 1원 이상 입력해야 함');
  if(type==='deposit'){
    if(S.wallet.bal<a)return alert('보유 배당포인트가 부족함');S.wallet.bal-=a;S.wallet.vault+=a
  }else{
    if(S.wallet.vault<a)return alert('금고 잔액이 부족함');S.wallet.vault-=a;S.wallet.bal+=a;
    if(S.active&&S.active.reveal<0&&S.active.recoveryRequired&&!S.active.recovery&&S.wallet.bal>=130)S.active.recoveryRequired=false
  }
  S.wallet.vaultLog.unshift({type:type,n:S.last,amount:a,balance:S.wallet.vault,time:Date.now()});S.wallet.vaultLog=S.wallet.vaultLog.slice(0,100);vaultAmount=0;save();render()
}
function vaultLogHtml(){let log=S.wallet.vaultLog||[];return log.length?'<div class="history">'+log.map(x=>{let label=x.type==='interest'?'대회 이자':x.type==='deposit'?'보관':'인출',sign=x.type==='withdraw'?'+':'',cls=x.type==='interest'?'positive':'';return'<div class="hitem vault-log"><div>'+label+'</div><div><small>'+(x.n?'제 '+x.n+'회 대회':'수동 거래')+'</small><br><b>금고 '+Number(x.balance||0).toLocaleString()+'원</b></div><b class="'+cls+'">'+sign+Number(x.amount||0).toLocaleString()+'원</b></div>'}).join('')+'</div>':'<div class="empty">금고 거래 기록 없음</div>'}
function renderVault(){let w=S.wallet,total=w.bal+w.vault;return'<div class="sectionhead"><div><h1>금고</h1><p>대회가 1회 완료될 때마다 금고 잔액에 0.1% 복리 이자가 지급됨</p></div></div><div class="card vault-hero"><div class="vault-balance"><div><span>금고 잔액</span><b>'+w.vault.toLocaleString()+'원</b></div><div><span>누적 이자</span><b class="positive">+'+w.interest.toLocaleString()+'원</b></div></div><div class="vault-rate"><span>대회당 이자율</span><b>0.1%</b><small>다음 대회 예상 이자 '+Math.floor(w.vault*.001).toLocaleString()+'원</small></div></div><div class="card"><div class="summary"><div class="sum"><span>사용 가능</span><b>'+w.bal.toLocaleString()+'원</b></div><div class="sum"><span>금고 보관</span><b>'+w.vault.toLocaleString()+'원</b></div><div class="sum"><span>총자산</span><b>'+total.toLocaleString()+'원</b></div><div class="sum"><span>최근 이자</span><b>+'+w.lastInterest.toLocaleString()+'원</b></div></div><div class="target-label vault-label"><span>보관·인출 금액</span><small>버튼을 누르면 금액 누적</small></div><div class="amount-quick vault-quick"><button onclick="addVaultAmount(100)">+100</button><button onclick="addVaultAmount(1000)">+1,000</button><button onclick="addVaultAmount(10000)">+10,000</button><button onclick="addVaultAmount(100000)">+100,000</button></div><div class="amount-input vault-input"><input id="vaultAmount" type="number" inputmode="numeric" min="0" value="'+vaultAmount+'" oninput="setVaultAmount(this.value)" aria-label="금고 거래 금액"><button class="btn" onclick="clearVaultAmount()">초기화</button></div><div class="vault-max"><button onclick="maxVaultAmount(\'deposit\')">보유금액 전액</button><button onclick="maxVaultAmount(\'withdraw\')">금고 전액</button></div><div class="modal-actions"><button class="btn gold" onclick="vaultTransaction(\'deposit\')">금고에 보관</button><button class="btn primary" onclick="vaultTransaction(\'withdraw\')">금고에서 인출</button></div></div><div class="card"><h3 style="margin-top:0">금고 거래·이자 기록</h3>'+vaultLogHtml()+'</div>'}
function renderPlayer(){let w=S.wallet,p=S.player||{champStars:0},tier=moneyTier(w.bal),total=w.bal+w.vault,next=tier.next,progress=next?Math.min(100,Math.max(0,(w.bal-tier.min)/(next-tier.min)*100)):100;return'<div class="sectionhead"><div><h1>플레이어 정보</h1><p>보유 배당포인트 등급과 우승팀 베팅 업적을 확인할 수 있음</p></div></div><div class="player-profile"><div class="player-profile-head"><div class="player-avatar">♛</div><div><small>WORLD CUP PREDICTOR</small><h2>플레이어</h2><span>완료 대회 '+S.total.toLocaleString()+'회</span></div><em>'+tier.name+' 등급</em></div><div class="balance-frame tier-'+tier.key+'"><span>보유 배당포인트</span><b>'+w.bal.toLocaleString()+'원</b><small>'+(next?'다음 등급까지 '+Math.max(0,next-w.bal).toLocaleString()+'원':'최고 등급 달성')+'</small><i style="width:'+progress+'%"></i></div><div class="player-assets"><div><span>금고</span><b>'+w.vault.toLocaleString()+'원</b></div><div><span>총자산</span><b>'+total.toLocaleString()+'원</b></div><div><span>우승 베팅 적중</span><b>'+p.champStars.toLocaleString()+'회</b></div><div><span>전체 베팅 적중률</span><b>'+((w.hit+w.miss)?(w.hit/(w.hit+w.miss)*100).toFixed(1):'0.0')+'%</b></div></div></div><div class="card achievement-card"><div class="achievement-head"><div><h3>우승팀 예측 업적</h3><p>구제예측을 제외한 우승 목표 베팅 적중 1회마다 별 1개 획득</p></div><b>'+p.champStars+' STAR</b></div>'+starSlots(p.champStars)+'<div class="star-progress"><span>'+starTierText(p.champStars)+'</span><small>흰색 → 동 → 은 → 금 → 플레티넘 → 다이아 → 루비 → 흑요석</small></div></div><div class="card tier-guide"><h3>배당포인트 프레임 등급</h3><div class="tier-list"><span>100만원 동</span><span>1,000만원 은</span><span>1억원 금</span><span>10억원 플레티넘</span><span>100억원 다이아</span><span>1,000억원 루비</span><span>1조원 흑요석</span></div></div><div class="card"><h3 style="margin-top:0">최근 베팅</h3>'+renderBetHistory()+'</div>'}
function renderBetHistory(){let w=S.wallet;return'<div class="history">'+(w.log.length?w.log.map(x=>'<div class="hitem"><div>제 '+x.n+'회</div><div>'+team(x.team)+'<br><small>'+ST[x.target]+' · '+(x.odds?x.odds.toFixed(2)+'배':'구제 예측')+(x.opp?' · vs '+T[x.opp][0]:'')+(x.achievement?' · ★ 업적':'')+'</small></div><b class="'+(x.profit>=0?'positive':'negative')+'">'+(x.profit>=0?'+':'')+x.profit.toLocaleString()+'</b></div>').join(''):'<div class="empty">베팅 기록 없음</div>')+'</div>'}
function openTeam(c){let z=S.teams[c],p=T[c][5];document.getElementById('modal').innerHTML='<div class="modalbg" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modalhead"><h2>'+team(c)+'</h2><button class="close" onclick="closeModal()">×</button></div><div class="summary"><div class="sum"><span>팀 전력</span><b>'+rating(c)+'</b></div><div class="sum"><span>조</span><b>'+T[c][2]+'조</b></div><div class="sum"><span>결승 확률</span><b>'+pct(z.fin)+'</b></div><div class="sum"><span>우승 확률</span><b>'+pct(z.win)+'</b></div></div><button class="btn" style="width:100%;margin-top:9px" onclick="openJourney(\''+c+'\')">현재 대회 진출 경로 보기</button><h3>단계별 누적 확률</h3><div class="walletgrid">'+SK.map((k,i)=>'<button class="statbtn" onclick="openRecords(\''+c+'\',\''+k+'\')"><span>'+ST[i]+'</span><b>'+pct(z[k])+'</b></button>').join('')+'</div><h3>핵심 선수</h3><div class="players">'+p.map(x=>'<div class="player"><span>'+esc(x[0])+' · '+x[1]+'</span><b>'+x[2]+'</b></div>').join('')+'</div></div></div>'}
function resultForTeam(m,c){let own=m.a===c?m.ga:m.gb,opp=m.a===c?m.gb:m.ga,res=own>opp?'승':own<opp?'패':'무';if(m.pen){let p=m.a===c?m.pen:[m.pen[1],m.pen[0]];res=p[0]>p[1]?'승':'패';return{own:own,opp:opp,res:res,pen:p}}return{own:own,opp:opp,res:res,pen:null}}
function revealedJourney(c,t,reveal){let out=[];
  if(reveal>=0&&(t.gm||[]).length)(t.gm||[]).filter(m=>m.a===c||m.b===c).forEach(m=>{let r=resultForTeam(m,c),o=m.a===c?m.b:m.a;out.push({stage:'조별',opp:o,score:r.own+'-'+r.opp,result:r.res,pen:r.pen})});
  let labels=['32강','16강','8강','4강','결승'];for(let i=0;i<5;i++)if(reveal>=i+1){let m=(t.rounds[i]||[]).find(x=>x.a===c||x.b===c);if(m){let r=resultForTeam(m,c),o=m.a===c?m.b:m.a;out.push({stage:labels[i],opp:o,score:r.own+'-'+r.opp,result:r.res,pen:r.pen})}}
  return out
}
function journeyRows(rows){return rows.length?'<div class="journey-list">'+rows.map(x=>'<div class="journey-item '+(x.result==='승'?'win':x.result==='패'?'loss':'')+'"><span class="stage">'+x.stage+'</span><div class="versus"><b>vs '+team(x.opp)+'</b><small>'+x.result+(x.pen?' · 승부차기 '+x.pen[0]+'-'+x.pen[1]:'')+'</small></div><span class="score">'+x.score+'</span></div>').join('')+'</div>':'<div class="empty">아직 공개된 경기 결과가 없음</div>'}
function currentFinish(c,t,reveal){if(reveal<0)return'대회 시작 전';let key=SK[Math.min(reveal,5)],alive=!!(t.reach&&t.reach[key]&&t.reach[key].has(c));if(reveal===5){if(t.champ===c)return'우승';if(t.runner===c)return'준우승'}if(alive)return stageName(reveal)+' 생존';let rows=revealedJourney(c,t,reveal),last=rows[rows.length-1];return last?last.stage+' 탈락':'조별리그 탈락'}
function openJourney(c){let src=historyTour?expand(historyTour):S.active?S.active.t:null,reveal=historyTour?5:S.active?S.active.reveal:-1;if(!src)return alert('진행 중인 대회가 없음');let rows=revealedJourney(c,src,reveal);document.getElementById('modal').innerHTML='<div class="modalbg" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modalhead"><h2>'+team(c)+' 진출 경로</h2><button class="close" onclick="closeModal()">×</button></div><div class="notice"><b>'+currentFinish(c,src,reveal)+'</b><br>공개된 경기까지만 표시하며 이후 라운드 결과는 노출하지 않음</div><div style="margin-top:9px">'+journeyRows(rows)+'</div></div></div>'}
function openRecords(c,k){let arr=S.archives.filter(a=>expand(a).reach[k].has(c)).reverse();document.getElementById('modal').innerHTML='<div class="modalbg" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modalhead"><h2>'+team(c)+' · '+ST[SK.indexOf(k)]+'</h2><button class="close" onclick="closeModal()">×</button></div><div class="notice">누적 '+S.teams[c][k].toLocaleString()+'회 · 저장된 최근 대진 '+arr.length+'회</div><div class="history" style="margin-top:9px">'+(arr.length?arr.map(a=>'<button class="hitem" style="color:white;text-align:left" onclick="showArchive('+a.n+')"><span>제 '+a.n+'회</span><span>우승 '+team(a.champ)+'</span><b>대진표 ›</b></button>').join(''):'<div class="empty">저장된 대진 기록 없음</div>')+'</div></div></div>'}
function betDecisiveHtml(data){let b=data.bet;if(b.target===0){let rows=revealedJourney(b.team,data.tour,0);return'<div class="notice" style="margin-top:9px">조별리그 3경기 결과를 기준으로 32강 진출 여부가 확정됐음</div><div style="margin-top:8px">'+journeyRows(rows)+'</div>'}if(data.match){let r=resultForTeam(data.match,b.team),row={stage:ST[b.target-1],opp:data.opp,score:r.own+'-'+r.opp,result:r.res,pen:r.pen};return'<div class="notice" style="margin-top:9px">목표 라운드 진출 여부를 결정한 경기</div><div style="margin-top:8px">'+journeyRows([row])+'</div>'}let rows=revealedJourney(b.team,data.tour,data.reveal);return'<div class="notice" style="margin-top:9px">목표 라운드 이전에 탈락하여 가장 최근 공개 경기 결과를 표시함</div><div style="margin-top:8px">'+journeyRows(rows.slice(-1))+'</div>'}
function recoveryResultHtml(d){let rows=revealedJourney(d.team,d.tour,d.reveal),last=rows.slice(-1);if(d.hit){let fm=(d.tour.rounds[4]||[])[0],r=fm?resultForTeam(fm,d.team):null,row=fm?{stage:'결승',opp:fm.a===d.team?fm.b:fm.a,score:r.own+'-'+r.opp,result:r.res,pen:r.pen}:null;return'<div class="notice" style="margin-top:9px">구제 우승 예측이 적중하여 10,000원이 지급됐음</div>'+(row?'<div style="margin-top:8px">'+journeyRows([row])+'</div>':'')}
  return'<div class="notice" style="margin-top:9px">예측 국가가 우승 경쟁에서 탈락하여 구제 예측이 실패했음</div><div style="margin-top:8px">'+journeyRows(last)+'</div>'
}
function showRecoveryResult(d){document.getElementById('modal').innerHTML='<div class="modalbg"><div class="modal"><div class="modalhead"><h2>구제 우승 예측 결과</h2><button class="close" onclick="closeModal()">×</button></div><div class="result-hero '+(d.hit?'hit':'miss')+'"><div class="icon">'+(d.hit?'🎁':'✕')+'</div><h3>'+team(d.team)+' · '+(d.hit?'우승 예측 적중':'우승 예측 실패')+'</h3><p>무료 구제 예측 · 적중 보상 10,000원</p></div>'+recoveryResultHtml(d)+'<div class="result-money"><div><span>예측 참가비</span><b>무료</b></div><div><span>지급액</span><b>'+d.pay.toLocaleString()+'원</b></div><div><span>현재 보유금액</span><b>'+S.wallet.bal.toLocaleString()+'원</b></div><div><span>재도전</span><b>'+(d.hit?'구제 모드 종료':'다음 대회 가능')+'</b></div></div><button class="btn primary" style="width:100%;margin-top:10px" onclick="closeModal()">확인</button></div></div>'}
function showNextBetResult(){if(!pendingBetResults.length)return;let d=pendingBetResults.shift();if(d.type==='recovery')return showRecoveryResult(d);let b=d.bet,profit=d.hit?b.pay-b.stake-b.fee:-b.stake-b.fee,award=b.achievement?'<div class="achievement-award"><span>★</span><div><b>우승팀 예측 업적 별 획득</b><small>플레이어 정보의 별이 1개 추가됐음</small></div></div>':'';document.getElementById('modal').innerHTML='<div class="modalbg"><div class="modal"><div class="modalhead"><h2>베팅 결과 · '+ST[b.target]+'</h2><button class="close" onclick="closeModal()">×</button></div><div class="result-hero '+(d.hit?'hit':'miss')+'"><div class="icon">'+(d.hit?'🎯':'✕')+'</div><h3>'+team(b.team)+' · '+(d.hit?'목표 달성':'목표 미달')+'</h3><p>'+ST[b.target]+' 진출 베팅 · '+b.odds.toFixed(2)+'배</p></div>'+award+betDecisiveHtml(d)+'<div class="result-money"><div><span>베팅액 + 수수료</span><b>'+b.stake.toLocaleString()+' + '+b.fee.toLocaleString()+'원</b></div><div><span>지급액</span><b>'+b.pay.toLocaleString()+'원</b></div><div><span>최종 순손익</span><b class="'+(profit>=0?'positive':'negative')+'">'+(profit>=0?'+':'')+profit.toLocaleString()+'원</b></div><div><span>현재 보유금액</span><b>'+S.wallet.bal.toLocaleString()+'원</b></div></div><button class="btn primary" style="width:100%;margin-top:10px" onclick="closeModal()">확인</button></div></div>'}
function showArchive(n){historyTour=S.archives.find(a=>a.n===n);bracketRound=0;closeModal(false);view='tour';render()}
function closeModal(checkQueue){document.getElementById('modal').innerHTML='';if(checkQueue!==false&&pendingBetResults.length)setTimeout(showNextBetResult,30)}
function openNewGameModal(){document.getElementById('modal').innerHTML='<div class="modalbg" onclick="if(event.target===this)closeModal(false)"><div class="modal new-game-modal"><div class="modalhead"><h2>새 게임 시작</h2><button class="close" onclick="closeModal(false)">×</button></div><div class="new-game-icon">↻</div><h3>처음부터 다시 시작할까요?</h3><p class="new-game-copy">현재 진행 중인 대회와 모든 누적 통계, 베팅 기록, 보유금액이 초기화됨</p><div class="new-game-reset-list"><div><span>초기 보유자금</span><b>'+STARTING_BALANCE.toLocaleString()+'원</b></div><div><span>누적 대회·통계</span><b>0회</b></div><div><span>베팅 기록·손익</span><b>전체 삭제</b></div></div><div class="modal-actions"><button class="btn" onclick="closeModal(false)">취소</button><button class="btn danger" onclick="startNewGame()">새 게임 시작</button></div></div></div>'}
function startNewGame(){S=fresh();view='tour';historyTour=null;selectedTeam=C.slice().sort((a,b)=>rating(b)-rating(a))[0];selectedTarget=0;amount=0;vaultAmount=0;bracketRound=0;pendingBetResults=[];busy=false;prepare(true);save();closeModal(false);render();setTimeout(function(){document.getElementById('modal').innerHTML='<div class="modalbg" onclick="if(event.target===this)closeModal(false)"><div class="modal new-game-complete"><div class="new-game-icon complete">✓</div><h3>새 게임이 시작됐음</h3><p class="new-game-copy">초기 보유자금 '+STARTING_BALANCE.toLocaleString()+'원으로 제1회 월드컵이 준비됐음</p><button class="btn primary" style="width:100%" onclick="closeModal(false)">확인</button></div></div>'},30)}
function resetAll(){openNewGameModal()}
function renderNav(){let n=[['tour','🏆','대회'],['stats','📊','통계'],['teams','🌍','국가'],['vault','🏦','금고'],['player','👤','플레이어']];document.getElementById('nav').innerHTML=n.map(x=>'<button class="'+(view===x[0]?'on':'')+'" onclick="view=\''+x[0]+'\';historyTour=null;render()"><i>'+x[1]+'</i>'+x[2]+'</button>').join('')}
function render(){renderNav();document.getElementById('money').textContent=S.wallet.bal.toLocaleString()+'원';document.getElementById('topStatus').textContent=S.active?stageName(S.active.reveal):'누적 '+S.total.toLocaleString()+'회';document.getElementById('app').innerHTML=view==='tour'?renderTour():view==='stats'?renderStats():view==='teams'?renderTeams():view==='vault'?renderVault():renderPlayer()}
window.addEventListener('error',function(e){console.log(e.message)});if(!S.active)prepare(true);render();
