function renderTeams(){let a=C.slice().sort((x,y)=>rating(y)-rating(x));return'<div class="sectionhead"><div><h1>48개 참가국</h1><p>국가를 누르면 전력·핵심 선수·단계별 확률 확인 가능</p></div></div><div class="cards">'+a.map(c=>'<button class="teamcard" onclick="openTeam(\''+c+'\')"><div>'+team(c)+'</div><small>'+T[c][2]+'조 · 전력 '+rating(c)+'</small><div class="metrics"><div><b>'+pct(S.teams[c].r32)+'</b><span>32강</span></div><div><b>'+pct(S.teams[c].fin)+'</b><span>결승</span></div><div><b>'+pct(S.teams[c].win)+'</b><span>우승</span></div></div></button>').join('')+'</div>'}
function renderWallet(){let w=S.wallet;return'<div class="sectionhead"><div><h1>베팅 지갑</h1><p>수수료는 적중 여부와 관계없이 반환되지 않음</p></div></div><div class="card"><div class="walletgrid"><div><span>보유금액</span><b>'+w.bal.toLocaleString()+' BP</b></div><div><span>누적 손익</span><b class="'+(w.profit>=0?'positive':'negative')+'">'+w.profit.toLocaleString()+'</b></div><div><span>누적 수수료</span><b>'+w.fee.toLocaleString()+'</b></div><div><span>적중</span><b>'+w.hit+'</b></div><div><span>실패</span><b>'+w.miss+'</b></div><div><span>구제 적중</span><b>'+w.recoveryHit+'/'+w.recoveryTry+'</b></div></div></div><div class="card"><h3 style="margin-top:0">최근 베팅</h3><div class="history">'+(w.log.length?w.log.map(x=>'<div class="hitem"><div>제 '+x.n+'회</div><div>'+team(x.team)+'<br><small>'+ST[x.target]+' · '+(x.odds?x.odds.toFixed(2)+'배':'구제 예측')+(x.opp?' · vs '+T[x.opp][0]:'')+'</small></div><b class="'+(x.profit>=0?'positive':'negative')+'">'+(x.profit>=0?'+':'')+x.profit.toLocaleString()+'</b></div>').join(''):'<div class="empty">베팅 기록 없음</div>')+'</div></div>'}
function openTeam(c){let z=S.teams[c],p=T[c][5];document.getElementById('modal').innerHTML='<div class="modalbg" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modalhead"><h2>'+team(c)+'</h2><button class="close" onclick="closeModal()">×</button></div><div class="summary"><div class="sum"><span>팀 전력</span><b>'+rating(c)+'</b></div><div class="sum"><span>조</span><b>'+T[c][2]+'조</b></div><div class="sum"><span>결승 확률</span><b>'+pct(z.fin)+'</b></div><div class="sum"><span>우승 확률</span><b>'+pct(z.win)+'</b></div></div><button class="btn" style="width:100%;margin-top:9px" onclick="openJourney(\''+c+'\')">현재 대회 진출 경로 보기</button><h3>단계별 누적 확률</h3><div class="walletgrid">'+SK.map((k,i)=>'<button class="statbtn" onclick="openRecords(\''+c+'\',\''+k+'\')"><span>'+ST[i]+'</span><b>'+pct(z[k])+'</b></button>').join('')+'</div><h3>핵심 선수</h3><div class="players">'+p.map(x=>'<div class="player"><span>'+esc(x[0])+' · '+x[1]+'</span><b>'+x[2]+'</b></div>').join('')+'</div></div></div>'}
function resultForTeam(m,c){let own=m.a===c?m.ga:m.gb,opp=m.a===c?m.gb:m.ga,res=own>opp?'승':own<opp?'패':'무';if(m.pen){let p=m.a===c?m.pen:[m.pen[1],m.pen[0]];res=p[0]>p[1]?'승':'패';return{own:own,opp:opp,res:res,pen:p}}return{own:own,opp:opp,res:res,pen:null}}
function revealedJourney(c,t,reveal){let out=[];
  if(reveal>=0&&(t.gm||[]).length)(t.gm||[]).filter(m=>m.a===c||m.b===c).forEach(m=>{let r=resultForTeam(m,c),o=m.a===c?m.b:m.a;out.push({stage:'조별',opp:o,score:r.own+'-'+r.opp,result:r.res,pen:r.pen})});
  let labels=['32강','16강','8강','4강','결승'];for(let i=0;i<5;i++)if(reveal>=i+1){let m=(t.rounds[i]||[]).find(x=>x.a===c||x.b===c);if(m){let r=resultForTeam(m,c),o=m.a===c?m.b:m.a;out.push({stage:labels[i],opp:o,score:r.own+'-'+r.opp,result:r.res,pen:r.pen})}}
  return out
}
function journeyRows(rows){return rows.length?'<div class="journey-list">'+rows.map(x=>'<div class="journey-item '+(x.result==='승'?'win':x.result==='패'?'loss':'')+'"><span class="stage">'+x.stage+'</span><div class="versus"><b>vs '+team(x.opp)+'</b><small>'+x.result+(x.pen?' · 승부차기 '+x.pen[0]+'-'+x.pen[1]:'')+'</small></div><span class="score">'+x.score+'</span></div>').join('')+'</div>':'<div class="empty">아직 공개된 경기 결과가 없음</div>'}
function currentFinish(c,t,reveal){if(reveal<0)return'대회 시작 전';let alive=stageAlive(reveal).includes(c);if(reveal===5){if(t.champ===c)return'우승';if(t.runner===c)return'준우승'}if(alive)return stageName(reveal)+' 생존';let rows=revealedJourney(c,t,reveal),last=rows[rows.length-1];return last?last.stage+' 탈락':'조별리그 탈락'}
function openJourney(c){let src=historyTour?expand(historyTour):S.active?S.active.t:null,reveal=historyTour?5:S.active?S.active.reveal:-1;if(!src)return alert('진행 중인 대회가 없음');let rows=revealedJourney(c,src,reveal);document.getElementById('modal').innerHTML='<div class="modalbg" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modalhead"><h2>'+team(c)+' 진출 경로</h2><button class="close" onclick="closeModal()">×</button></div><div class="notice"><b>'+currentFinish(c,src,reveal)+'</b><br>공개된 경기까지만 표시하며 이후 라운드 결과는 노출하지 않음</div><div style="margin-top:9px">'+journeyRows(rows)+'</div></div></div>'}
function openRecords(c,k){let arr=S.archives.filter(a=>expand(a).reach[k].has(c)).reverse();document.getElementById('modal').innerHTML='<div class="modalbg" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modalhead"><h2>'+team(c)+' · '+ST[SK.indexOf(k)]+'</h2><button class="close" onclick="closeModal()">×</button></div><div class="notice">누적 '+S.teams[c][k].toLocaleString()+'회 · 저장된 최근 대진 '+arr.length+'회</div><div class="history" style="margin-top:9px">'+(arr.length?arr.map(a=>'<button class="hitem" style="color:white;text-align:left" onclick="showArchive('+a.n+')"><span>제 '+a.n+'회</span><span>우승 '+team(a.champ)+'</span><b>대진표 ›</b></button>').join(''):'<div class="empty">저장된 대진 기록 없음</div>')+'</div></div></div>'}
function betDecisiveHtml(data){let b=data.bet;if(b.target===0){let rows=revealedJourney(b.team,data.tour,0);return'<div class="notice" style="margin-top:9px">조별리그 3경기 결과를 기준으로 32강 진출 여부가 확정됐음</div><div style="margin-top:8px">'+journeyRows(rows)+'</div>'}if(data.match){let r=resultForTeam(data.match,b.team),row={stage:ST[b.target-1],opp:data.opp,score:r.own+'-'+r.opp,result:r.res,pen:r.pen};return'<div class="notice" style="margin-top:9px">목표 라운드 진출 여부를 결정한 경기</div><div style="margin-top:8px">'+journeyRows([row])+'</div>'}let rows=revealedJourney(b.team,data.tour,data.reveal);return'<div class="notice" style="margin-top:9px">목표 라운드 이전에 탈락하여 가장 최근 공개 경기 결과를 표시함</div><div style="margin-top:8px">'+journeyRows(rows.slice(-1))+'</div>'}
function showNextBetResult(){if(!pendingBetResults.length)return;let d=pendingBetResults.shift(),b=d.bet,profit=d.hit?b.pay-b.stake-b.fee:-b.stake-b.fee;document.getElementById('modal').innerHTML='<div class="modalbg"><div class="modal"><div class="modalhead"><h2>베팅 결과 · '+ST[b.target]+'</h2><button class="close" onclick="closeModal()">×</button></div><div class="result-hero '+(d.hit?'hit':'miss')+'"><div class="icon">'+(d.hit?'🎯':'✕')+'</div><h3>'+team(b.team)+' · '+(d.hit?'목표 달성':'목표 미달')+'</h3><p>'+ST[b.target]+' 진출 베팅 · '+b.odds.toFixed(2)+'배</p></div>'+betDecisiveHtml(d)+'<div class="result-money"><div><span>베팅액 + 수수료</span><b>'+b.stake.toLocaleString()+' + '+b.fee.toLocaleString()+' BP</b></div><div><span>지급액</span><b>'+b.pay.toLocaleString()+' BP</b></div><div><span>최종 순손익</span><b class="'+(profit>=0?'positive':'negative')+'">'+(profit>=0?'+':'')+profit.toLocaleString()+' BP</b></div><div><span>현재 보유금액</span><b>'+S.wallet.bal.toLocaleString()+' BP</b></div></div><button class="btn primary" style="width:100%;margin-top:10px" onclick="closeModal()">확인</button></div></div>'}
function showArchive(n){historyTour=S.archives.find(a=>a.n===n);bracketRound=0;closeModal(false);view='tour';render()}
function closeModal(checkQueue){document.getElementById('modal').innerHTML='';if(checkQueue!==false&&pendingBetResults.length)setTimeout(showNextBetResult,30)}
function resetAll(){if(confirm('누적 통계와 베팅 지갑을 모두 초기화할까요?')){S=fresh();prepare(true);save();render()}}
function renderNav(){let n=[['tour','🏆','대회'],['stats','📊','통계'],['teams','🌍','국가'],['wallet','💰','지갑']];document.getElementById('nav').innerHTML=n.map(x=>'<button class="'+(view===x[0]?'on':'')+'" onclick="view=\''+x[0]+'\';historyTour=null;render()"><i>'+x[1]+'</i>'+x[2]+'</button>').join('')}
function render(){renderNav();document.getElementById('money').textContent=S.wallet.bal.toLocaleString()+' BP';document.getElementById('topStatus').textContent=S.active?stageName(S.active.reveal):'누적 '+S.total.toLocaleString()+'회';document.getElementById('app').innerHTML=view==='tour'?renderTour():view==='stats'?renderStats():view==='teams'?renderTeams():renderWallet()}
window.addEventListener('error',function(e){console.log(e.message)});if(!S.active)prepare(true);render();
