function renderTeams(){let a=C.slice().sort((x,y)=>rating(y)-rating(x));return'<div class="sectionhead"><div><h1>48개 참가국</h1><p>국가를 누르면 전력·핵심 선수·단계별 확률 확인 가능</p></div></div><div class="cards">'+a.map(c=>'<button class="teamcard" onclick="openTeam(\''+c+'\')"><div>'+team(c)+'</div><small>'+T[c][2]+'조 · 전력 '+rating(c)+'</small><div class="metrics"><div><b>'+pct(S.teams[c].r32)+'</b><span>32강</span></div><div><b>'+pct(S.teams[c].fin)+'</b><span>결승</span></div><div><b>'+pct(S.teams[c].win)+'</b><span>우승</span></div></div></button>').join('')+'</div>'}
function renderWallet(){let w=S.wallet;return'<div class="sectionhead"><div><h1>베팅 지갑</h1><p>수수료는 적중 여부와 관계없이 반환되지 않음</p></div></div><div class="card"><div class="walletgrid"><div><span>보유금액</span><b>'+w.bal.toLocaleString()+' BP</b></div><div><span>누적 손익</span><b class="'+(w.profit>=0?'positive':'negative')+'">'+w.profit.toLocaleString()+'</b></div><div><span>누적 수수료</span><b>'+w.fee.toLocaleString()+'</b></div><div><span>적중</span><b>'+w.hit+'</b></div><div><span>실패</span><b>'+w.miss+'</b></div><div><span>구제 적중</span><b>'+w.recoveryHit+'/'+w.recoveryTry+'</b></div></div></div><div class="card"><h3 style="margin-top:0">최근 베팅</h3><div class="history">'+(w.log.length?w.log.map(x=>'<div class="hitem"><div>제 '+x.n+'회</div><div>'+team(x.team)+'<br><small>'+ST[x.target]+' · '+(x.odds?x.odds.toFixed(2)+'배':'구제 예측')+'</small></div><b class="'+(x.profit>=0?'positive':'negative')+'">'+(x.profit>=0?'+':'')+x.profit.toLocaleString()+'</b></div>').join(''):'<div class="empty">베팅 기록 없음</div>')+'</div></div>'}
function openTeam(c){let z=S.teams[c],p=T[c][5];document.getElementById('modal').innerHTML='<div class="modalbg" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modalhead"><h2>'+team(c)+'</h2><button class="close" onclick="closeModal()">×</button></div><div class="summary"><div class="sum"><span>팀 전력</span><b>'+rating(c)+'</b></div><div class="sum"><span>조</span><b>'+T[c][2]+'조</b></div><div class="sum"><span>결승 확률</span><b>'+pct(z.fin)+'</b></div><div class="sum"><span>우승 확률</span><b>'+pct(z.win)+'</b></div></div><h3>단계별 누적 확률</h3><div class="walletgrid">'+SK.map((k,i)=>'<button class="statbtn" onclick="openRecords(\''+c+'\',\''+k+'\')"><span>'+ST[i]+'</span><b>'+pct(z[k])+'</b></button>').join('')+'</div><h3>핵심 선수</h3><div class="players">'+p.map(x=>'<div class="player"><span>'+esc(x[0])+' · '+x[1]+'</span><b>'+x[2]+'</b></div>').join('')+'</div></div></div>'}
function openRecords(c,k){let arr=S.archives.filter(a=>expand(a).reach[k].has(c)).reverse();document.getElementById('modal').innerHTML='<div class="modalbg" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modalhead"><h2>'+team(c)+' · '+ST[SK.indexOf(k)]+'</h2><button class="close" onclick="closeModal()">×</button></div><div class="notice">누적 '+S.teams[c][k].toLocaleString()+'회 · 저장된 최근 대진 '+arr.length+'회</div><div class="history" style="margin-top:9px">'+(arr.length?arr.map(a=>'<button class="hitem" style="color:white;text-align:left" onclick="showArchive('+a.n+')"><span>제 '+a.n+'회</span><span>우승 '+team(a.champ)+'</span><b>대진표 ›</b></button>').join(''):'<div class="empty">저장된 대진 기록 없음</div>')+'</div></div></div>'}
function showArchive(n){historyTour=S.archives.find(a=>a.n===n);closeModal();view='tour';render()}
function closeModal(){document.getElementById('modal').innerHTML=''}
function resetAll(){if(confirm('누적 통계와 베팅 지갑을 모두 초기화할까요?')){S=fresh();save();render()}}
function renderNav(){let n=[['tour','🏆','대회'],['stats','📊','통계'],['teams','🌍','국가'],['wallet','💰','지갑']];document.getElementById('nav').innerHTML=n.map(x=>'<button class="'+(view===x[0]?'on':'')+'" onclick="view=\''+x[0]+'\';historyTour=null;render()"><i>'+x[1]+'</i>'+x[2]+'</button>').join('')}
function render(){renderNav();document.getElementById('money').textContent=S.wallet.bal.toLocaleString()+' BP';document.getElementById('topStatus').textContent=S.active?stageName(S.active.reveal):'누적 '+S.total.toLocaleString()+'회';document.getElementById('app').innerHTML=view==='tour'?renderTour():view==='stats'?renderStats():view==='teams'?renderTeams():renderWallet()}
window.addEventListener('error',function(e){console.log(e.message)});render();
